server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db1
    username: root
    password: root
mybatis:
  type-aliases-package: com.manu.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka,http://localhost:8001/eureka
  instance:
    lease-renewal-interval-in-seconds: 30 #最小注册周期，秒
    lease-expiration-duration-in-seconds: 90 #最小过期时长，秒