server:
  port: 8000
spring:
  application:
    name: eureka-server-manu
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    register-with-eureka: false # 此注释表示eureka不再自己注册自己
  server:
    eviction-interval-timer-in-ms: 30000 #注册失效剔除，默认是隔30秒进行剔除，单位毫秒。

